on:
    workflow_call:
    pull_request:

jobs:
    get_changed_files:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch origin ${{ github.ref }}
            raw_files="$(git diff --name-only)"
            if [ raw_files ]; then
                url_prefix="https://deploy-preview-"
                url_postscript="--app-services.netlify.app/"
                pr_number="foo"
                base_url="$url_prefix$pr_number$url_postscript"
                console.log(base_url)
                files = rawFiles.split('\n')
                for file in files; do
                    link = base_url + file
                    console.log(link)
            fi
                # now write the paths to the PR template.
            done