on:
    workflow_call:
    pull_request:

jobs:
    get_changed_files:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch origin ${{ github.ref }}
            raw_files="$(git diff --name-only)"
            # console.log($raw_files)
            # if [ raw_files ]; then
                base_url="https://deploy-preview-"
                base_url+=${{ github.event.number }} 
                base_url+="--app-services.netlify.app/"
                console.log("$base_url")
                files = rawFiles.split('\n')
                for file in files; do
                    link = base_url + file
                    console.log("$link")
                done
            # fi
                # now write the paths to the PR template.
        

