on:
    workflow_call:
    pull_request:

jobs:
    get_changed_files:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch origin ${{ github.ref }}
            raw_files="$(gh pr view ${{ github.event.number }})"
            echo "$raw_files"
          env:
            GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
       