on:
    workflow_call:
    pull_request:

# env:
#   GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }} # setting GH_TOKEN for the entire workflow

jobs:
    foo:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - uses: actions/checkout@v3
        - run: |
            git remote -v 
            echo ${{ github.head_ref }}
            echo ${{ github.base_ref }}
            echo ${{github.ref}}
            git fetch origin
            gh pr view 
#links_action
#master
#refs/pull/789/merge
            #gh pr checkout $BRANCH

          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: ${{ github.head_ref }}