on:
    workflow_call:
    pull_request:

# env:
#   GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }} # setting GH_TOKEN for the entire workflow

jobs:
    foo:
        runs-on: ubuntu-latest
        steps:
        - run: |
            ls -l

          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}