on:
    workflow_call:
    pull_request:

# env:
#   GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }} # setting GH_TOKEN for the entire workflow

jobs:
    foo:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - uses: actions/checkout@v3
        - run: |
            git fetch origin ${{ github.ref }}
            ls -l
            gh pr view
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}