on:
    workflow_call:
    pull_request:

# env:
#   GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }} # setting GH_TOKEN for the entire workflow

jobs:
    foo:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        - uses: actions/checkout@v3
        - run: |
            git pull origin ${{ github.ref }} --rebase
            ls -l
            gh pr diff master --name-only
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: ${{ github.head_ref }}