on:
    workflow_call:
    pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr view $PR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
