on:
    workflow_call:
    pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
        run: gh pr view $PR
